### PR TITLE
Add more ES6 rules

### PR DESCRIPTION
**Pull request by elliottsj**
See http://eslint.org/docs/rules/#ecmascript-6

### CODE REVIEW

**Comment by SashaSirotkin** [comment]
@elliottsj This is a breaking change for people using ES5.

**Comment by elliottsj** [comment]
@SashaSirotkin yep, this'll require a major version bump (v0.3.0). One of these days I'm going to learn how to use [jscodeshift](https://github.com/facebook/jscodeshift) so we can migrate all the old code: https://www.youtube.com/watch?v=d0pOgY8__JM

**Comment by SashaSirotkin** [comment]
@elliottsj It would be `0.2.0` -> `1.0.0` since major is the left-most number.

**Comment by elliottsj** [comment]
@SashaSirotkin Before reaching 1.0.0, semver treats the second number as the breaking-change number. e.g. on http://jubianchi.github.io/semver-check/:

screenshot 2015-12-01 14 51 01
screenshot 2015-12-01 14 51 08

**Comment by SashaSirotkin** [comment]
@elliottsj I learned something today!

**Comment by SashaSirotkin** [comment]
:zap:

**Pull request merged**
