### PR TITLE
Upgrade airbnb-config to 11.1 and 7.1

### PR DESCRIPTION
**Pull request by CNBorn**
## What does this PR do?
- Upgrade eslint-config-airbnb to 11.1 and eslint-config-airbnb-base to 7.1
- Mainly because I want this feature: https://github.com/airbnb/javascript/commit/38f679e9f90b8d9699477f4dc4c2914691b5f247
- Are there any tests I need to run for this?

### CODE REVIEW

**Comment by droustchev** [comment]
lgtm :rocket:

**Comment by ainth** [comment]
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md
and
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md

**Comment by ainth** [comment]
Should update the eslint dependency in package.json since the changelog says they've updated to 3.5.0

**Comment by ainth** [comment]
No tests to run, need to do a separate PR to bump the version then `npm publish`

**Comment by droustchev** [comment]
I found the changelogs after I commented, so I edited my comment back :D

**Comment by CNBorn** [comment]
@ainth eslint ^3.5.0 updated in this PR. btw can I bump the version in this PR as well? does it required to be a separate PR? if it does, why?

**Comment by ainth** [comment]
Just a bit cleaner. Then the commit message can be clear that this is the point when the version changed and the new version was published. Guess it makes as much sense to have it as a separate commit in this PR

Example: https://github.com/EventMobi/eslint-config-eventmobi/commit/ac15f3fce2ecdeae3f720b78c1420782ea4dd3ef

**Comment by CNBorn** [comment]
@ainth Just got back to this one :) Added a commit to bump the version and I'll make & push the release tag (on the merged commit) once this PR got merged. That's all I should do right?

**Comment by ainth** [comment]
Sounds good 🚀

**Comment by CNBorn** [comment]
Tags pushed [v0.14.3](https://github.com/EventMobi/eslint-config-eventmobi/tree/v0.14.3)

**Pull request merged**
